env:
  DEPLOY_TEST_ROLE_ARN: "arn:aws:iam::576424575048:role/DevOpsToolingAppDeployRole"
  DEPLOY_STAGE_ROLE_ARN: "arn:aws:iam::422397319486:role/DevOpsToolingAppDeployRole"
  DEPLOY_PROD_ROLE_ARN: "arn:aws:iam::247334077905:role/DevOpsToolingAppDeployRole"
  DEPLOY_TEST_ECR: "576424575048.dkr.ecr.ap-southeast-2.amazonaws.com"
  DEPLOY_STAGE_ECR: "422397319486.dkr.ecr.ap-southeast-2.amazonaws.com"
  DEPLOY_PROD_ECR: "247334077905.dkr.ecr.ap-southeast-2.amazonaws.com"


steps:
  - block: ":rocket: Deploy Branch To Test"
    branches: "!master"
  - label: ":package: Test - Build Backend Project"
    command:
      - "echo 'Running Build & Push for container"
    env:
      AWS_ASSUME_ROLE_ARN: ${DEPLOY_TEST_ROLE_ARN}
    branches: "!master"
    plugins:
      - cultureamp/aws-assume-role
      - seek-oss/docker-ecr-publish#v2.4.0:
          dockerfile: Dockerfile
          account_id: "576424575048"
          region: "ap-southeast-2"
          add-latest-tag: false
          ecr-name: gtbackend
          args: COMMIT_SHA=$BUILDKITE_COMMIT
  
  - wait  
  - label: ":rocket: Deploy Branch to Test"
    command:
      - "echo 'Deploying Branch to ECS...'"
      - "./ecs-deploy -c ecs-spot-test -n givetree-backend -i ${DEPLOY_TEST_ECR}/gtbackend:$$BUILDKITE_BUILD_NUMBER -t 600 --enable-rollback"
    branches: "!master"
    env:
      AWS_ASSUME_ROLE_ARN: ${DEPLOY_TEST_ROLE_ARN}
    plugins:
      - cultureamp/aws-assume-role
  
  - wait  

  - block: ":rocket: Deploy Master To Staging"
    branches: "master"

  - label: ":package: Staging - Build Backend Project"
    command:
      - "echo 'Running Build & Push for container"
    env:
      AWS_ASSUME_ROLE_ARN: ${DEPLOY_STAGE_ROLE_ARN}
    branches: "master"
    plugins:
      - cultureamp/aws-assume-role
      - seek-oss/docker-ecr-publish#v2.4.0:
          dockerfile: Dockerfile
          account_id: "422397319486"
          region: "ap-southeast-2"
          add-latest-tag: false
          ecr-name: gtbackend
          args: COMMIT_SHA=$BUILDKITE_COMMIT
  
  - wait  

  - label: ":rocket: Deploy Master to Staging"
    command:
      - "echo 'Deploying Master to Staging ECS...'"
      - "./ecs-deploy -c givetree -n givetree-backend -i ${DEPLOY_STAGE_ECR}/gtbackend:$$BUILDKITE_BUILD_NUMBER -t 600 --enable-rollback"
    branches: "master"
    env:
      AWS_ASSUME_ROLE_ARN: ${DEPLOY_STAGE_ROLE_ARN}
    plugins:
      - cultureamp/aws-assume-role
      
  - wait  

  - block: ":rocket: Deploy Master To Production"
    branches: "master"

  - label: ":package: Production - Build Backend Project"
    command:
      - "echo 'Running Build & Push for container"
    env:
      AWS_ASSUME_ROLE_ARN: ${DEPLOY_PROD_ROLE_ARN}
    branches: "master"
    plugins:
      - cultureamp/aws-assume-role
      - seek-oss/docker-ecr-publish#v2.4.0:
          dockerfile: Dockerfile
          account_id: "247334077905"
          region: "ap-southeast-2"
          add-latest-tag: false
          ecr-name: gtbackend
          args: COMMIT_SHA=$BUILDKITE_COMMIT
  
  - wait  

  - label: ":rocket: Deploy Master to Production"
    command:
      - "echo 'Deploying Master to Production ECS...'"
      - "./ecs-deploy -c givetree -n givetree-backend -i ${DEPLOY_PROD_ECR}/gtbackend:$$BUILDKITE_BUILD_NUMBER -t 600 --enable-rollback"
    branches: "master"
    env:
      AWS_ASSUME_ROLE_ARN: ${DEPLOY_PROD_ROLE_ARN}
    plugins:
      - cultureamp/aws-assume-role